version: "3"

services:
  pgsj:

    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    image: "mirghaeng/pgsj:1.0"
    container_name: "pg-container"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgsj_db

    ports:
      - "5432:5432"

    volumes:
      - pg-data:/var/lib/postgresql/data

        #networks:
        #node_net:
        #ipv4_address: 175.0.0.1

volumes:
  pg-data:
    external: true

    #networks:
    #node_net:
    #ipam:
    #  driver: default
    #  config:
    #    - subnet: 175.0.0.0/1
